#!/sbin/openrc-run
directory="/var/lib/fishbb" 
command="/usr/local/bin/fishbb"
command_user="alex"
pidfile="/run/$RC_SVCNAME/$RC_SVCNAME.pid"
command_background="yes"
output_log="/var/log/fishbb.log"
error_log="/var/log/fishbb.log"

start_pre() {
    checkpath -d --owner $command_user:$command_user --mode 0755 /run/$RC_SVCNAME
    checkpath -f --owner $command_user:$command_user --m 0775 /var/log/fishbb.log
}
